parameters:
#    ktu_core.example.class: KTU\CoreBundle\Example

services:
#    ktu_core.example:
#        class: %ktu_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
